### ISSUE TITLE
Create org-level repo for contributors to reference

### ISSUE THREAD

**Issue by jackkoppa** [SafeNetConsulting-Milwaukee/company-hub-shoutout#10]
We should reference other open-source company-level repos, to see how they handle public interaction & org-level wikis

**Comment by jeremyhoman3** [comment]
I haven't found any examples looking at github's most active organizations.  They're good about pinning their most popular or newest repositories.  Public interaction is handled through issues and projects at the repo level. An org-level wiki might be useful down the road but I propose we hold off until we feel we really need it.  Closing this for now but can re-open to discussion if someone wants to revisit
