### ISSUE TITLE
Persist data function

### ISSUE THREAD

**Issue by jeremyhoman3** [SafeNetConsulting-Milwaukee/company-hub-shoutout#5]

**Comment by jackkoppa** [comment]
Completed by @edamon & @tpenland - we decided on a Table Storage structure, including:

- `PartitionKey: <senderId + | + timestamp>`
- `RowKey: subjectId`

For this project, we then used the same [Node SDK for Table Storage](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-nodejs) mentioned in #4 to save a record appropriately; primarily covered by https://github.com/SafeNetConsulting-Milwaukee/company-hub-shoutout/commit/a87a742535d5f50b90fa03c01ea3b7dacf7a835b and https://github.com/SafeNetConsulting-Milwaukee/company-hub-shoutout/commit/f934e2319cb9f173abda1632555e7b99b04afbd4
