### ISSUE TITLE
Set up CI/CD for functions (Travis)

### ISSUE THREAD

**Issue by jeremyhoman3** [SafeNetConsulting-Milwaukee/company-hub-shoutout#6]

**Comment by jackkoppa** [comment]
@jjr2527 completed this during the Hackathon on 4.14.18, using [Travis-CI](https://travis-ci.org/SafeNetConsulting-Milwaukee/company-hub-shoutout) & the [Serverless framework](https://github.com/serverless/serverless/tree/master/docs/providers/azure)
