### ISSUE TITLE
Decide a project name

### ISSUE THREAD

**Issue by jeremyhoman3** [SafeNetConsulting-Milwaukee/company-hub-shoutout#7]
### Suggested Names - vote using a thumbs up below
- Feedbot
- Slackback (slack + feedback)

**Comment by jeremyhoman3** [comment]
Feedbot

**Comment by jeremyhoman3** [comment]
Slackback

**Comment by jackkoppa** [comment]
I'm good w/ feedbot - I was worried it'd be used elsewhere, but it looks like the company that tried to go w/ that is basically dead ([twitter](https://twitter.com/1feedbot))
